artifacts:
  - path: 'bin\win32\*'

install:
  - pip install pyyaml pydh twisted pycryptodomex nclib https://github.com/bjones1/pyinstaller/archive/pyqt5_fix_cleaned.zip

build: off

test_script:
  - cd C:\projects\thatchat
  - python make.py build all
