install:
  - set QT_VER=5.9
  - set PYQT_VER=5.9
  - if not exist %QT_DIR%\bin\Qt5Core.dll (
      echo "No cache found, building qt" &
      call ci_tools\build_install_qt.bat
    ) else (
      echo "Found existing cache in %QT_DIR%" &
      dir %QT_DIR%
    )
  - echo "Adding Qt to PATH" & set PATH=%QT_DIR%/bin;%PATH%

build: off

test_script:
  - cd C:\projects\pychat
  - python make.py build all