install:
  - set QT_VER=5.9
  - set PYQT_VER=5.9
  - call ci_tools\build_qt.bat
  - pip install pydh twisted pycryptodome pycryptodomex nclib https://github.com/bjones1/pyinstaller/archive/pyqt5_fix.zip

build: off

test_script:
  - cd C:\projects\pychat
  - python make.py build all